/**:
  ros__parameters:
    node_name: "mcl"
    # map_name: "/map"
    # scan_name: "/scan"
    # odom_name: "/odom"
    # gl_sampled_poses_name: "/gl_sampled_poses"
    # local_map_name: "/gl_local_map"
    # sdf_keypoints_name: "/gl_sdf_keypoints"
    # local_sdf_keypoints_name: "/gl_local_sdf_keypoints"
    # map_frame: "map"
    # odom_frame: "odom"
    # base_link_frame: "base_link"
    # laser_frame: "laser"
    # residual_errors_name: "/residual_errors"
    pose_name: "/mcl_pose"
    particles_name: "/mcl_particles"
    unknown_scan_name: "/unknown_scan"
    reliability_marker_name: "/reliability_marker_name"
    broadcast_tf: true
    use_odom_tf: false
    initial_pose_x: 0.0
    initial_pose_y: 0.0
    initial_pose_yaw: 0.0
    initial_noise_x: 0.02
    initial_noise_y: 0.02
    initial_noise_yaw: 0.01
    measurement_model_type: 2
    particle_num: 1000
    use_augmented_mcl: false
    alpha_slow: 0.001
    alpha_fast: 0.99
    add_random_particles_in_resampling: true
    use_omni_directional_model: false
    reject_unknown_scan: false
    publish_unknown_scan: true
    unknown_scan_prob_threshold: 0.9
    publish_residual_errors: true
    scan_step: 5
    z_hit: 0.9
    z_short: 0.2
    z_max: 0.05
    z_rand: 0.05
    var_hit: 0.08
    lambda_short: 1.0
    lambda_unknown: 0.01
    known_class_prior: 0.5
    resample_threshold_ess: 0.5
    estimate_reliability: true
    classifier_type: 0
    mae_classifier_dir: "/home/apollo-22/als_ros2/src/als_ros/classifiers/MAE/gifu_univ_7th/"
    mae_max_residual_error: 0.5
    mae_histrogram_bin_width: 0.05
    fuse_gl_pose_sampler_only_unreliable: false
    gl_sampled_pose_time_th: 1.0
    gmm_positional_variance: 0.01
    gmm_angular_variance: 0.01
    pred_dist_unif_rate: 0.05
    write_pose: true
    pose_log_file: "/tmp/als_ros2_pose.txt"
    localization_hz: 10.0
    transform_tolerance: 0.0
    random_particles_noise:
      - 0.05
      - 0.05
      - 0.1
    odom_noise_ddm:
      - 1.0
      - 0.5
      - 0.5
      - 1.5
    odom_noise_odm:
      - 4.0
      - 1.0
      - 1.0
      - 1.0
      - 4.0
      - 1.0
      - 1.0
      - 1.0
      - 8.0
    rel_trans_ddm:
      - 0.0
      - 0.0
    rel_trans_odm:
      - 0.0
      - 0.0
      - 0.0
    resample_tresholds:
      - 0.2
      - 0.2
      - 0.2
      - 0.02
      - -99999.0
